name: integration_flutter_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  equatable: '^2.0.3'
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  get_it: ^7.2.0
  bloc: ^8.1.1
  table_calendar: ^3.0.9
  provider: ^6.0.5
  intl: ^0.18.1
  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/icons/
    - assets/img/storage/
    - assets/img/inspection/
    - assets/img/error/


