name: integration_flutter_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  equatable: '^2.0.3'
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1
  get_it: ^7.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/icons/


